### ISSUE TITLE
Node-Red Flow Example is a Dead Link

### ISSUE THREAD

**Issue by bdbuysse** [mifbody/EcobeeNodeRed#1]
Hello,

There is a dead-link referenced in the readme.  
https://github.com/mifbody/EcobeeNodeRed/blob/master/ecobeeflow.txt

**Comment by jtmoderate876** [comment]
You can instead go to here:
https://github.com/mifbody/EcobeeNodeRed/blob/master/ecobee-BlueMix.json

or here:
https://github.com/mifbody/EcobeeNodeRed/blob/master/ecobee-Local.json
